### ISSUE TITLE
OpenPGP support?

### ISSUE THREAD

**Issue by nimbius** [solokeys/solo1#16]
any chance getting openpgp support added?

**Comment by nickray** [comment]
Hi @nimbius, yes extendability is a major goal of this project, thank you for asking.
We will communicate a public roadmap after the Kickstarter is over, but adding support for GPG, SSH, static passwords and more will definitely be part of it :)

**Comment by binaryplease** [comment]
> Hi @nimbius, yes extendability is a major goal of this project, thank you for asking.
> We will communicate a public roadmap after the Kickstarter is over, but adding support for GPG, SSH, static passwords and more will definitely be part of it :)

Is this "public roadmap" out yet? Any progress on GPG/SSH? I would be very interested in seeing a GPG and SSH implementation. Actually this would be the main thing I would like to use this key for. Having my private keys not leaving the device would be great.

**Comment by pjz** [comment]
Related: http://www.fsij.org/category/gnuk.html - runs on a STM32F103, but doesn't do FIDO or etc, only OpenPGP card protocol version 2.

**Comment by michaelblyons** [comment]
For anyone lurking here who hadn't noticed yet, you may be interested in [`solokeys/openpgp`](https://github.com/solokeys/openpgp).

**Comment by lopezator** [comment]
@michaelblyons sorry for the silly question, but this need the hacker edition I guess?

**Comment by manuel-domke** [comment]
@lopezator:  fYes, a Solo Hacker is required to test and develop that firmware version.

At least as long as there is no officially signed firmware for it, which will probably only happen when it's stable.

**Comment by manuel-domke** [comment]
@lopezator:  Yes, a Solo Hacker is required to test and develop that firmware version.

At least as long as there is no officially signed firmware for it, which will probably only happen when it's stable.

**Comment by sakoula** [comment]
hi, is there any progress on this? So currently there is no way to store gpg or ssh keys on solo, right?

**Comment by Frederick888** [comment]
@sakoula You can, but only on Hacker versions if I understand correctly.

**Comment by sakoula** [comment]
@Frederick888 Thanks! I just have the regular version. 

I recall that when I signed up for the kickstarter one of the 'selling' points was support for gpg/ssh keys. Any idea if there are any plans of a soon-to-released firmware supporting these features?

Thanks!

**Comment by janisz** [comment]
I think they need more money and try to collect it on https://www.crowdsupply.com/solokeys/somu#stretch-goals
> $100k - SSH/GPG - we’ll invest part of the funding to speed up the implementation of SSH/GPG support, starting with ECDSA keys.

**Comment by conorpp** [comment]
We are still working on it here:
https://github.com/solokeys/openpgp

Still have some testing and porting to do.  If you want it faster, [consider backing our Somu campaign](https://www.crowdsupply.com/solokeys/somu#stretch-goals), which will continue to fund this effort!  And you get another cool key :)

**Comment by Frederick888** [comment]
> https://www.crowdsupply.com/solokeys/somu#stretch-goals

Hmm... I've already got a USB-C Solo Tap and at least for now I haven't got a need for a mini security key (tbh I don't think leaving your security key plugged into your computer is a good practice). I would probably consider backing the campaign if there's a Tap Hacker option but that would lead to effectively less fund for Somu I guess (a little off-topic...).

**Comment by lopezator** [comment]
@Frederick888 you can configure & store in a safe a Somu as a backup in case you lose your main key, that indeed would be a food practice.

**Comment by lf94** [comment]
So uh, what happened?

**Comment by lf94** [comment]
@conorpp ?

**Comment by wucke13** [comment]
This for sure is not the right place. but I want to state this somewhere: I bought the original SoloKey, and the Somu. I convinced friends to do so as well. I will, however, not buy any more Solo stuff as long as this issue can not be closed. Make it a real alternative to YubiKey!

**Comment by nimbius** [comment]
Solov2 just released (I funded it this morning) and surprise, no mention of pgp. :/

This is not a terribly difficult undertaking.  I hope to see more activity in this effort in 2021 and will eagerly test and debug any firmware offered for the v2.  



On January 26, 2021 8:22:32 AM PST, wucke13 <notifications@github.com> wrote:
>This for sure is not the right place. but I want to state this somewhere: I bought the original SoloKey, and the Somu. I convinced friends to do so as well. I will, however, not buy any more Solo stuff as long as this issue can not be closed. Make it a real alternative to YubiKey!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/solokeys/solo/issues/16#issuecomment-767658070
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nickray** [comment]
Yes, the appropriate place would be https://github.com/solokeys/kickstarter2021/discussions.

**Comment by 06kellyjac** [comment]
Or if you fund the Solo v2 you can fill out the survey (you'll receive a message about it) and mention this issue towards the end

**Comment by dudeisbrendan03** [comment]
Any chances of OpenGPG support being introduced to the Solo 1?

**Comment by maweil** [comment]
How about voting which gpg use cases would be the most important and implementing a small subset of the functionality only?
If the hardware of Solo v1 is not sufficient for a GnuPG Smartcard Implementation, exposing some vendor commands for signing or decrypting might be an option.

I'd be really happy to see at least the signing capabilities written by @rgerganov in PR #397 in the official firmware.

**Comment by larcenou** [comment]
> Hi @nimbius, yes extendability is a major goal of this project, thank you for asking. We will communicate a public roadmap after the Kickstarter is over, but adding support for GPG, SSH, static passwords and more will definitely be part of it :)

I bought my first solo 5 years ago - the promise of active work on pgp implementation was a major reason for me to buy several more over the years. Today I have to admit it’s getting really disappointing to read the same phrase in the FAQ and still no pgp update rolled out.

**Comment by kevinbarbour** [comment]
I agree, I also purchased my Solokey under the impression that PGP support was right around the corner. It's been a very disappointing product with the lack of effort they've put into achieving these early roadmap goals.

**Comment by jans23** [comment]
For those interested in an alternative, our [Nitrokey 3](https://www.nitrokey.com/products/nitrokeys) has full OpenPGP Card support. It's also based on Trussed, the same firmware framework Solokey is using (and written in Rust).

**Comment by Scrumplex** [comment]
Nitrokey was also on my radar as an alternative to Solokeys. I wonder if people made custom cases for the Nitrokey 3, because I personally think they don't *look* as appealing as a SoloKeys key.

**Comment by larcenou** [comment]
> For those interested in an alternative, our [Nitrokey 3](https://www.nitrokey.com/products/nitrokeys) has full OpenPGP Card support. It's also based on Trussed, the same firmware framework Solokey is using (and written in Rust).

Does the Nitrokey 3c NFC also support using PGP via NFC? If yes I would immediately order at least 3 of them.

**Comment by lf94** [comment]
@jans23 
> For those interested in an alternative, our [Nitrokey 3](https://www.nitrokey.com/products/nitrokeys) has full OpenPGP Card support. It's also based on Trussed, the same firmware framework Solokey is using (and written in Rust).

If we have proof of purchase of SoloKey v1s can we get a free Nitrokey? :slightly_smiling_face: 

I spent about $100 to get 3 SoloKeys just to have them be pretty much useless.

I would be an instant Nitrokey evangelist, praising.

**Comment by jans23** [comment]
OpenPGP Card works via USB only, not NFC.

I'm not aware of any custom made casings but feel free to do so.

**Comment by larcenou** [comment]
on my very old Yubikey PGP does work via NFC

**Comment by nimbius** [comment]
solo2 is out and the roadmap looks like PIV is the teams primary focus :-1:

**Comment by nimbius** [comment]
solo2 is out and the roadmap looks like PIV is the teams primary focus 👎

**Comment by michaelblyons** [comment]
Change close type to Not Planned?
