### ISSUE TITLE
Question: AAGUID

### ISSUE THREAD

**Issue by FaganSC** [solokeys/solo1#523]
Is there a way to obtain the AAGUID of a Solo Tap? Trying to configure my Solo Tap with Azure AD, and they now have the ability to add organizational approved devices if you have the AAGUID .

![image](https://user-images.githubusercontent.com/810028/109366465-809f0c80-7861-11eb-9a35-c2315edbce4d.png)

**Comment by aseigler** [comment]
See https://docs.solokeys.dev/metadata-statements/

**Comment by FaganSC** [comment]
I'm thinking it might take a little bit for Microsoft to push it out because I'm still getting the following error message after putting the AAGUID in for Azure AD.

![image](https://user-images.githubusercontent.com/810028/109371306-5275f880-7872-11eb-97ae-099d51de66ca.png)

**Comment by aseigler** [comment]
It definitely works if you turn off the key restrictions.

**Comment by back2root** [comment]
@FaganSC checkout: https://github.com/solokeys/solo/tree/master/metadata
Solo Tap should have aaguid: 8976631b-d4a0-427f-5773-0ec71c9e0279
