### ISSUE TITLE
Is the crypto hardware accelerated?

### ISSUE THREAD

**Issue by skannan89** [solokeys/solo1#588]
Hello,

Looks like the MCU supports hardware acceleration of certain crypto algorithms. Does solo support it?

Thanks!

**Comment by coelner** [comment]
Solo v1: https://www.st.com/en/microcontrollers-microprocessors/stm32l432kc.html
Solo v2: https://www.nxp.com/products/processors-and-microcontrollers/arm-microcontrollers/general-purpose-mcus/lpc5500-cortex-m33/high-efficiency-arm-cortex-m33-based-microcontroller-family:LPC55S6x

I did not see any embedded crypto for the solo v1.

**Comment by nickray** [comment]
Correct, there is no acceleration on Solo 1.
On Solo 2 there is a crypto coprocessor, which is currently not used. It may be used in future firmware updates. At least for p256, our implementation is faster than the vendor's SDK example 😅.
